### ISSUE TITLE
V[8] Hr module crash and account report crash  [tested on the last build of odoo]

### ISSUE THREAD

**Issue by sharkutz** [odoo-romania/l10n-romania#91]
Log: 
File "/opt/odoo/custom_addons/l10n_ro_hr/hr_employee.py", line 25, in <module>
    from stdnum.ro.cnp import get_birth_date, is_valid as validate_cnp
ImportError: No module named stdnum.ro.cnp

2015-04-04 22:21:51,436 28538 ERROR test db openerp.sql_db: Programming error: column product_product.d394_id does not exist
LINE 1: ...t_product"."ean13","product_product"."write_date","product_p...
                                                             ^
, in query  SELECT "product_product"."create_date","product_product"."active","product_product"."product_tmpl_id","product_product"."create_uid","product_product"."id","product_product"."ean13","product_product"."write_date","product_product"."d394_id","product_product"."default_code","product_product"."write_uid","product_product"."name_template","product_product"."message_last_post" FROM "product_product"
                        WHERE "product_product".id IN %s  ORDER BY "product_product"."default_code" ,"product_product"."name_template"

ProgrammingError: column "module_l10n_ro_partner_unique" of relation "l10n_ro_config_settings" does not exist
LINE 1: ...10n_ro_zipcode", "module_l10n_ro_invoice_report", "module_l1...

2015-04-04 22:23:17,526 28538 ERROR neozivdb_production openerp.sql_db: Programming error: column "module_l10n_ro_partner_unique" of relation "l10n_ro_config_settings" does not exist
LINE 1: ...10n_ro_zipcode", "module_l10n_ro_invoice_report", "module_l1...
                                                             ^
, in query INSERT INTO "l10n_ro_config_settings" ("id", "module_account_compensation", "module_l10n_ro_stock_account", "module_account_vat_on_payment", "module_l10n_ro_asset", "module_l10n_ro_invoice_line_not_deductible", "module_l10n_ro_currency_reevaluation", "module_l10n_ro_stock", "module_l10n_ro_fiscal_validation", "module_l10n_ro_account_compensation_currency_update", "siruta_update", "module_l10n_ro_account_bank_statement", "module_l10n_ro_account_report", "company_id", "module_l10n_ro_zipcode", "module_l10n_ro_invoice_report", "module_l10n_ro_partner_unique", "module_l10n_ro_account_voucher_currency_update", "module_l10n_ro_siruta", "has_default_company", "module_partner_create_by_vat", "module_l10n_ro_stock_picking_report", "module_l10n_ro_account_constrains", "module_l10n_ro_account_period_close", "module_l10n_ro_account_voucher_cash", "module_currency_rate_update", "module_account_storno", "create_uid", "write_uid", "create_date", "write_date") VALUES(nextval('l10n_ro_config_settings_id_seq'), %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, (now() at time zone 'UTC'), (now() at time zone 'UTC')) RETURNING id

**Comment by feketemihai** [comment]
See issue #59 and try to update stdnum with pip install --upgrade stdnum. For unique of partners please pull the latest code and update all modules.

**Comment by sharkutz** [comment]
I'm using Ubuntu 12.04 and the stdnum version with this is 0.6. To install 0.9 and above: pip install https://pypi.python.org/packages/source/p/python-stdnum/python-stdnum-1.0.tar.gz

The rest still testing.

**Comment by sharkutz** [comment]
Doesn't work with the new install stdnum; latest odoo build and latest l10n_ro:

File "/opt/odoo/custom_addons/l10n_ro_hr/hr_employee.py", line 25, in <module>
    from stdnum.ro.cnp import get_birth_date, is_valid as validate_cnp
ImportError: No module named ro.cnp

Does wthis work only with odoo-romania repository and the custom addons have to be in the root of the odoo directory? 
Any preconditions to make this work?

**Comment by feketemihai** [comment]
For me worked with 0.9 version, i had as well 0.6 and after upgrade was ok. It should work without any other conditions.

**Comment by sharkutz** [comment]
Clean system ubuntu12.04 + odoo+ l10n_ro and deleted ./local and now it works(Hr module).
But still have some issues with Siruta and Zip codes and Ro_City.

Any insights on that?

**Comment by feketemihai** [comment]
For that you will need the odoo branch from odoo-romania or at least to replace the l10n-ro from odoo with the one from odoo-romania branch...

**Comment by sharkutz** [comment]
I see, just did a kdiff based on your commits on odoo-romania and you've made some changes.
Do you recommend using the odoo-romania repository (functional differences or just partners and banks added?). 
Thank you!

**Comment by feketemihai** [comment]
Differences are on bank statement operation, product category being multi company, the l10n-ro module which was not merged on time for v8...i will create a new pr for v8 and master for romanian localisation. In a few weeks the project will be moved under OCA and the differences will be replaced with extra modules...for bank operation there is already a module under OCA.

**Comment by feketemihai** [comment]
For zipcodes there is some work to do...the module was depending only by the l10n-ro module...but when the Siruta module appeared the zipcodes depend on it and we need to remap the data with the new id's from siruta data files...

**Comment by sharkutz** [comment]
I've managed to install everything (no siruta and zip) but now I get this error when I try to create a product! 
   res = self._obj.execute(query, params)
ProgrammingError: column product_product.d394_id does not exist
LINE 1: ..._product"."ean13","product_product"."create_date","product_p...

**Comment by sharkutz** [comment]
I looked over some commits and you;ve changed the d394_ids to d394_id
Can it be that?

**Comment by feketemihai** [comment]
No...if you update all the modules there should not be any error.

**Comment by sharkutz** [comment]
I've done a clean install: no more errors when installing the modules but when I had to create a product I got and error. This is the error from the log:

**Comment by sharkutz** [comment]
, in query  SELECT product_product__product_tmpl_id."uos_coeff",product_product__product_tmpl_id."weight",product_product__product_tmpl_id."uos_id",product_product__product_tmpl_id."weight_net",product_product__product_tmpl_id."categ_id","product_product"."id",product_product__product_tmpl_id."company_id",product_product__product_tmpl_id."sale_line_warn_msg",product_product__product_tmpl_id."sale_delay",product_product__product_tmpl_id."product_manager",product_product__product_tmpl_id."website_sequence",product_product__product_tmpl_id."track_production",product_product__product_tmpl_id."purchase_line_warn_msg",product_product__product_tmpl_id."sale_line_warn",product_product__product_tmpl_id."state",product_product__product_tmpl_id."landed_cost_ok",product_product__product_tmpl_id."purchase_ok",product_product__product_tmpl_id."email_template_id","product_product"."d394_id",product_product__product_tmpl_id."sale_ok",product_product__product_tmpl_id."mes_type","product_product"."active","product_product"."product_tmpl_id",product_product__product_tmpl_id."website_published",product_product__product_tmpl_id."type",product_product__product_tmpl_id."loc_row",product_product__product_tmpl_id."loc_case",product_product__product_tmpl_id."split_method",product_product__product_tmpl_id."uom_id",product_product__product_tmpl_id."track_outgoing","product_product"."default_code",product_product__product_tmpl_id."intrastat_id",product_product__product_tmpl_id."uom_po_id",product_product__product_tmpl_id."volume",product_product__product_tmpl_id."loc_rack",product_product__product_tmpl_id."purchase_line_warn",product_product__product_tmpl_id."track_all","product_product"."ean13",product_product__product_tmpl_id."warranty",product_product__product_tmpl_id."produce_delay",product_product__product_tmpl_id."track_incoming" FROM "product_product","product_template" as "product_product__product_tmpl_id"
                        WHERE "product_product".id IN %s AND ("product_product"."product_tmpl_id" = "product_product__product_tmpl_id"."id")  ORDER BY "product_product"."default_code" ,"product_product"."name_template"

2015-04-05 16:51:16,997 10091 ERROR neozivdb_production openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/odooV8/openerp/http.py", line 530, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odooV8/openerp/http.py", line 567, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odooV8/openerp/http.py", line 303, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/http.py", line 300, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 796, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odooV8/openerp/http.py", line 396, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 935, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odooV8/addons/web/controllers/main.py", line 927, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3125, in read
    result = BaseModel.read(records, fields, load=load)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3160, in read
    self._read_from_database(stored, inherited)
  File "/opt/odoo/odooV8/openerp/api.py", line 239, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/models.py", line 3283, in _read_from_database
    cr.execute(query_str, [tuple(sub_ids)] + where_params)
  File "/opt/odoo/odooV8/openerp/sql_db.py", line 158, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odooV8/openerp/sql_db.py", line 234, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column product_product.d394_id does not exist
LINE 1: ...duct_product__product_tmpl_id."email_template_id","product_p...

**Comment by sharkutz** [comment]
ok, cloning odoo-romania and will test with that!

**Comment by feketemihai** [comment]
@sharkutz You're living in Cluj?

**Comment by sharkutz** [comment]
yes

**Comment by sharkutz** [comment]
Well it seem to work with odoo-romania repository.
But if I try to transfer the database eCommerce module won't work. 
you have to install and configure everything from the start. 
Restoring databases from Odoo to Odoo-romania is possible but will brake the eCommerce module.
The rest work ok.
jorza.andrei - please add skype id for more info and discussions, would like to get involved.
